defaults: &defaults
  fog_provider: "AWS"
  fog_directory: "hornsbybathroom-assets"
  aws_access_key_id: AKIAIRSHP5CQAJL3C6PQ
  aws_secret_access_key: 5rrw1vcm023TtTqSgdjrFppQMc7G0rjce/dNTREi
  # You may need to specify what region your storage bucket is in
  fog_region: "us-east-1"
  existing_remote_files: keep # Existing pre-compiled assets on S3 will be kept
  # To delete existing remote files.
  # existing_remote_files: delete
  # Automatically replace files with their equivalent gzip compressed version
  gzip_compression: true
  # Fail silently.  Useful for environments such as Heroku
  # fail_silently = true
  #http://lovebargains-assets.s3-website-us-east-1.amazonaws.com/

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults